#!/usr/bin/env bash

HOST_USER_ID=$(id -u "$(whoami)")
HOST_GROUP_ID=$(id -g "$(whoami)")

docker run                                      \
    --rm --interactive --tty                    \
    --user "${HOST_USER_ID}:${HOST_GROUP_ID}"   \
    --network coffee-machine_net                \
    --volume "$PWD":/app                        \
    --workdir /app                              \
    coffee-machine.php-cli                      \
    php index.php "$@"
